[tool.ruff]
line-length = 80
indent-width = 4

output-format = "grouped"

show-fixes = true

[tool.ruff.analyze]
detect-string-imports = true

[tool.ruff.format]
docstring-code-format = true
docstring-code-line-length = 40
indent-style = "space"
quote-style = "double"
skip-magic-trailing-comma = false

[tool.ruff.lint]
fixable = ["ALL"]
select=[
    "ERA",
    "ANN",
    "S",
    "FBT",
    "B",
    "COM",
    "C4",
    "DTZ",
    "FIX",
    "ISC",
    "LOG",
    "G",
    "PIE",
    "T20",
    "PT",
    "Q",
    "RET",
    "SLF",
    "SIM",
    "TC",
    "ARG",
    "PTH",
    "FLY",
    "I",
    "N",
    "E",
    "W",
    "D",
    "F",
    "PL",
    "PLC",
    "PLE",
    "PLR",
    "PLW",
    "FURB"
]
ignore = ["COM812", "D203", "D211", "D213"]
